server:
    port: 8888
spring:
    application:
        name: erudio-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/oFernandoLima/microsservices-java-spring-boot-erudio.git
                    # username: username
                    # password: password
                    default-label: main
                    search-paths:
                    - 'erudio-config-server/greeting-service*'